const generalKnowledgeQuestions = [
{ id: 1, level: "Basic", question: "Capital of Pakistan?", options: ["Lahore","Karachi","Islamabad","Peshawar"], answer: 2, answerString: "Islamabad" },
{ id: 2, level: "Basic", question: "2 + 2 = ?", options: ["3","4","5","6"], answer: 1, answerString: "4" },
{ id: 3, level: "Basic", question: "Largest continent?", options: ["Africa","Asia","Europe","Australia"], answer: 1, answerString: "Asia" },
{ id: 4, level: "Basic", question: "Color of sky?", options: ["Blue","Green","Red","Yellow"], answer: 0, answerString: "Blue" },
{ id: 5, level: "Basic", question: "National language of Pakistan?", options: ["English","Punjabi","Urdu","Sindhi"], answer: 2, answerString: "Urdu" },
{ id: 6, level: "Basic", question: "H2O is?", options: ["Salt","Water","Oxygen","Hydrogen"], answer: 1, answerString: "Water" },
{ id: 7, level: "Basic", question: "Fastest land animal?", options: ["Lion","Tiger","Cheetah","Horse"], answer: 2, answerString: "Cheetah" },
{ id: 8, level: "Basic", question: "5 × 3 = ?", options: ["10","15","20","25"], answer: 1, answerString: "15" },
{ id: 9, level: "Basic", question: "Sun rises from?", options: ["West","North","East","South"], answer: 2, answerString: "East" },
{ id: 10, level: "Basic", question: "National flower of Pakistan?", options: ["Rose","Jasmine","Tulip","Sunflower"], answer: 1, answerString: "Jasmine" },
{ id: 11, level: "Basic", question: "Largest planet?", options: ["Earth","Mars","Jupiter","Saturn"], answer: 2, answerString: "Jupiter" },
{ id: 12, level: "Basic", question: "1 dozen = ?", options: ["10","11","12","13"], answer: 2, answerString: "12" },
{ id: 13, level: "Basic", question: "Which is a mammal?", options: ["Shark","Whale","Frog","Snake"], answer: 1, answerString: "Whale" },
{ id: 14, level: "Basic", question: "Currency of USA?", options: ["Euro","Dollar","Pound","Rupee"], answer: 1, answerString: "Dollar" },
{ id: 15, level: "Basic", question: "7 days make a?", options: ["Month","Year","Week","Hour"], answer: 2, answerString: "Week" },
{ id: 16, level: "Basic", question: "Gas we breathe?", options: ["Oxygen","Nitrogen","Carbon","Hydrogen"], answer: 0, answerString: "Oxygen" },
{ id: 17, level: "Basic", question: "Square has how many sides?", options: ["3","4","5","6"], answer: 1, answerString: "4" },
{ id: 18, level: "Basic", question: "National animal of Pakistan?", options: ["Lion","Markhor","Tiger","Goat"], answer: 1, answerString: "Markhor" },
{ id: 19, level: "Basic", question: "Opposite of hot?", options: ["Warm","Cold","Cool","Boiling"], answer: 1, answerString: "Cold" },
{ id: 20, level: "Basic", question: "Computer brain is?", options: ["RAM","Hard Disk","CPU","Mouse"], answer: 2, answerString: "CPU" },
{ id: 21, level: "Basic", question: "Which is fruit?", options: ["Carrot","Potato","Apple","Onion"], answer: 2, answerString: "Apple" },
{ id: 22, level: "Basic", question: "10 ÷ 2 = ?", options: ["2","3","4","5"], answer: 3, answerString: "5" },
{ id: 23, level: "Basic", question: "How many months in year?", options: ["10","11","12","13"], answer: 2, answerString: "12" },
{ id: 24, level: "Basic", question: "First month of year?", options: ["January","March","April","June"], answer: 0, answerString: "January" },
{ id: 25, level: "Basic", question: "Bird that cannot fly?", options: ["Eagle","Crow","Penguin","Sparrow"], answer: 2, answerString: "Penguin" },
{ id: 26, level: "Basic", question: "1000 grams = ?", options: ["1kg","2kg","500g","100g"], answer: 0, answerString: "1kg" },
{ id: 27, level: "Basic", question: "Which is programming language?", options: ["HTML","Car","Table","Pen"], answer: 0, answerString: "HTML" },
{ id: 28, level: "Basic", question: "Color of grass?", options: ["Red","Green","Blue","Black"], answer: 1, answerString: "Green" },
{ id: 29, level: "Basic", question: "Which is device?", options: ["Mouse","Lion","Tree","Cloud"], answer: 0, answerString: "Mouse" },
{ id: 30, level: "Basic", question: "Earth is a?", options: ["Star","Planet","Moon","Comet"], answer: 1, answerString: "Planet" },
{ id: 31, level: "Intermediate", question: "Largest ocean in the world?", options: ["Indian","Pacific","Atlantic","Arctic"], answer: 1, answerString: "Pacific" },
{ id: 32, level: "Intermediate", question: "Who discovered gravity?", options: ["Newton","Einstein","Galileo","Tesla"], answer: 0, answerString: "Newton" },
{ id: 33, level: "Intermediate", question: "Speed of light?", options: ["3×10^8 m/s","3×10^6 m/s","3×10^5 m/s","300 m/s"], answer: 0, answerString: "3×10^8 m/s" },
{ id: 34, level: "Intermediate", question: "HTML stands for?", options: ["Hyper Trainer Marking Language","Hyper Text Markup Language","High Text Machine Language","None"], answer: 1, answerString: "Hyper Text Markup Language" },
{ id: 35, level: "Intermediate", question: "Chemical symbol of Gold?", options: ["Go","Au","Ag","Gd"], answer: 1, answerString: "Au" },
{ id: 36, level: "Intermediate", question: "First President of Pakistan?", options: ["Ayub Khan","Iskander Mirza","Jinnah","Liaquat Ali Khan"], answer: 1, answerString: "Iskander Mirza" },
{ id: 37, level: "Intermediate", question: "CPU stands for?", options: ["Central Process Unit","Central Processing Unit","Computer Personal Unit","Control Processing Unit"], answer: 1, answerString: "Central Processing Unit" },
{ id: 38, level: "Intermediate", question: "Largest desert?", options: ["Sahara","Gobi","Arabian","Thar"], answer: 0, answerString: "Sahara" },
{ id: 39, level: "Intermediate", question: "Which gas causes global warming?", options: ["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"], answer: 2, answerString: "Carbon Dioxide" },
{ id: 40, level: "Intermediate", question: "Binary of 5?", options: ["101","110","111","100"], answer: 0, answerString: "101" },
{ id: 41, level: "Intermediate", question: "Father of Computer?", options: ["Charles Babbage","Newton","Bill Gates","Alan Turing"], answer: 0, answerString: "Charles Babbage" },
{ id: 42, level: "Intermediate", question: "Which is prime number?", options: ["9","15","17","21"], answer: 2, answerString: "17" },
{ id: 43, level: "Intermediate", question: "UN was founded in?", options: ["1945","1939","1918","1950"], answer: 0, answerString: "1945" },
{ id: 44, level: "Intermediate", question: "RAM is?", options: ["Permanent","Temporary","Software","Input device"], answer: 1, answerString: "Temporary" },
{ id: 45, level: "Intermediate", question: "Longest river?", options: ["Nile","Amazon","Indus","Yangtze"], answer: 0, answerString: "Nile" },
{ id: 46, level: "Intermediate", question: "Java is?", options: ["OS","Programming Language","Hardware","Database"], answer: 1, answerString: "Programming Language" },
{ id: 47, level: "Intermediate", question: "Which planet is Red planet?", options: ["Mars","Venus","Jupiter","Mercury"], answer: 0, answerString: "Mars" },
{ id: 48, level: "Intermediate", question: "E = mc² proposed by?", options: ["Newton","Einstein","Tesla","Bohr"], answer: 1, answerString: "Einstein" },
{ id: 49, level: "Intermediate", question: "Smallest prime number?", options: ["0","1","2","3"], answer: 2, answerString: "2" },
{ id: 50, level: "Intermediate", question: "Which country has most population?", options: ["USA","India","China","Brazil"], answer: 2, answerString: "China" },
{ id: 51, level: "Intermediate", question: "Operating system example?", options: ["Windows","Keyboard","Mouse","Monitor"], answer: 0, answerString: "Windows" },
{ id: 52, level: "Intermediate", question: "Hard disk is?", options: ["Input","Output","Storage","Software"], answer: 2, answerString: "Storage" },
{ id: 53, level: "Intermediate", question: "Which is not programming language?", options: ["Python","C++","HTML","Lion"], answer: 3, answerString: "Lion" },
{ id: 54, level: "Intermediate", question: "Chemical formula of CO2?", options: ["Carbon Dioxide","Carbon Monoxide","Oxygen","Hydrogen"], answer: 0, answerString: "Carbon Dioxide" },
{ id: 55, level: "Intermediate", question: "Pakistan independence year?", options: ["1947","1956","1930","1965"], answer: 0, answerString: "1947" },
{ id: 56, level: "Intermediate", question: "Which is search engine?", options: ["Google","Facebook","WhatsApp","Instagram"], answer: 0, answerString: "Google" },
{ id: 57, level: "Intermediate", question: "Which layer in OSI is 7?", options: ["Application","Network","Data Link","Physical"], answer: 0, answerString: "Application" },
{ id: 58, level: "Intermediate", question: "Value of Pi?", options: ["3.14","2.14","4.13","3.41"], answer: 0, answerString: "3.14" },
{ id: 59, level: "Intermediate", question: "HTTP is?", options: ["Protocol","Language","Hardware","Virus"], answer: 0, answerString: "Protocol" },
{ id: 60, level: "Intermediate", question: "Which is database?", options: ["MySQL","Chrome","Word","Excel"], answer: 0, answerString: "MySQL" },
{ id: 61, level: "Expert", question: "Time complexity of Binary Search?", options: ["O(n)","O(log n)","O(n²)","O(1)"], answer: 1, answerString: "O(log n)" },
{ id: 62, level: "Expert", question: "Which sorting is fastest average case?", options: ["Bubble","Selection","Quick Sort","Insertion"], answer: 2, answerString: "Quick Sort" },
{ id: 63, level: "Expert", question: "IP version widely used?", options: ["IPv2","IPv4","IPv6","IPv8"], answer: 1, answerString: "IPv4" },
{ id: 64, level: "Expert", question: "SQL stands for?", options: ["Structured Query Language","Simple Query Language","Sequential Query Language","None"], answer: 0, answerString: "Structured Query Language" },
{ id: 65, level: "Expert", question: "Which is NoSQL database?", options: ["MySQL","MongoDB","Oracle","PostgreSQL"], answer: 1, answerString: "MongoDB" },
{ id: 66, level: "Expert", question: "TCP is?", options: ["Connection-oriented","Connectionless","Hardware","None"], answer: 0, answerString: "Connection-oriented" },
{ id: 67, level: "Expert", question: "Which is AI algorithm?", options: ["Linear Regression","Bubble Sort","Stack","Queue"], answer: 0, answerString: "Linear Regression" },
{ id: 68, level: "Expert", question: "Normal form 3NF removes?", options: ["Redundancy","Speed","Security","Memory"], answer: 0, answerString: "Redundancy" },
{ id: 69, level: "Expert", question: "Which is symmetric encryption?", options: ["AES","RSA","DSA","ECC"], answer: 0, answerString: "AES" },
{ id: 70, level: "Expert", question: "Recursion must have?", options: ["Loop","Base Case","Class","Object"], answer: 1, answerString: "Base Case" },
{ id: 71, level: "Expert", question: "Which is front-end framework?", options: ["React","Node","Django","Spring"], answer: 0, answerString: "React" },
{ id: 72, level: "Expert", question: "Big-O of Merge Sort?", options: ["O(n log n)","O(n²)","O(log n)","O(n)"], answer: 0, answerString: "O(n log n)" },
{ id: 73, level: "Expert", question: "Which port HTTP uses?", options: ["21","25","80","443"], answer: 2, answerString: "80" },
{ id: 74, level: "Expert", question: "Blockchain first used in?", options: ["Bitcoin","Facebook","Google","Amazon"], answer: 0, answerString: "Bitcoin" },
{ id: 75, level: "Expert", question: "Which is machine learning type?", options: ["Supervised","Sorting","Searching","Compiling"], answer: 0, answerString: "Supervised" },
{ id: 76, level: "Expert", question: "OSI has layers?", options: ["5","6","7","8"], answer: 2, answerString: "7" },
{ id: 77, level: "Expert", question: "Which is cloud platform?", options: ["AWS","CPU","RAM","SSD"], answer: 0, answerString: "AWS" },
{ id: 78, level: "Expert", question: "Deadlock occurs in?", options: ["OS","HTML","CSS","Mouse"], answer: 0, answerString: "OS" },
{ id: 79, level: "Expert", question: "Which is version control?", options: ["Git","Chrome","Word","Excel"], answer: 0, answerString: "Git" },
{ id: 80, level: "Expert", question: "Primary key must be?", options: ["Unique","Duplicate","Null","Optional"], answer: 0, answerString: "Unique" },
{ id: 81, level: "Expert", question: "Which is interpreted language?", options: ["Python","C","C++","Assembly"], answer: 0, answerString: "Python" },
{ id: 82, level: "Expert", question: "HTTPS uses?", options: ["SSL/TLS","FTP","SMTP","ARP"], answer: 0, answerString: "SSL/TLS" },
{ id: 83, level: "Expert", question: "Which is graph traversal?", options: ["DFS","Bubble","Insertion","Selection"], answer: 0, answerString: "DFS" },
{ id: 84, level: "Expert", question: "Data structure FIFO?", options: ["Stack","Queue","Tree","Graph"], answer: 1, answerString: "Queue" },
{ id: 85, level: "Expert", question: "Normalization is used in?", options: ["Database","HTML","CSS","Hardware"], answer: 0, answerString: "Database" },
{ id: 86, level: "Expert", question: "Which is API style?", options: ["REST","RAM","ROM","CPU"], answer: 0, answerString: "REST" },
{ id: 87, level: "Expert", question: "Which is hashing algorithm?", options: ["SHA-256","HTTP","FTP","TCP"], answer: 0, answerString: "SHA-256" },
{ id: 88, level: "Expert", question: "Which is programming paradigm?", options: ["OOP","USB","HDMI","LAN"], answer: 0, answerString: "OOP" },
{ id: 89, level: "Expert", question: "Which company created Java?", options: ["Sun Microsystems","Microsoft","Apple","IBM"], answer: 0, answerString: "Sun Microsystems" },
{ id: 90, level: "Expert", question: "Which is container tool?", options: ["Docker","Chrome","MySQL","Photoshop"], answer: 0, answerString: "Docker" }
];