const mathsQuestions = [
  // Basic Level (1-30)
  { id: 1, level: "Basic", question: "2 + 3 = ?", options: ["4","5","6","7"], answer: 1, answerString: "5" },
  { id: 2, level: "Basic", question: "5 - 2 = ?", options: ["2","3","4","5"], answer: 1, answerString: "3" },
  { id: 3, level: "Basic", question: "10 × 2 = ?", options: ["10","20","30","40"], answer: 1, answerString: "20" },
  { id: 4, level: "Basic", question: "12 ÷ 3 = ?", options: ["2","3","4","6"], answer: 2, answerString: "4" },
  { id: 5, level: "Basic", question: "Square of 5?", options: ["10","20","25","30"], answer: 2, answerString: "25" },
  { id: 6, level: "Basic", question: "Square root of 49?", options: ["6","7","8","9"], answer: 1, answerString: "7" },
  { id: 7, level: "Basic", question: "5 + 7 = ?", options: ["10","11","12","13"], answer: 2, answerString: "12" },
  { id: 8, level: "Basic", question: "10 - 6 = ?", options: ["3","4","5","6"], answer: 1, answerString: "4" },
  { id: 9, level: "Basic", question: "Multiplication of 6 × 6?", options: ["30","36","42","48"], answer: 1, answerString: "36" },
  { id: 10, level: "Basic", question: "10 ÷ 5 = ?", options: ["2","3","4","5"], answer: 0, answerString: "2" },
  { id: 11, level: "Basic", question: "7 + 8 = ?", options: ["13","14","15","16"], answer: 2, answerString: "15" },
  { id: 12, level: "Basic", question: "9 - 4 = ?", options: ["3","4","5","6"], answer: 2, answerString: "5" },
  { id: 13, level: "Basic", question: "Square of 8?", options: ["54","56","64","72"], answer: 2, answerString: "64" },
  { id: 14, level: "Basic", question: "Square root of 81?", options: ["8","9","10","11"], answer: 1, answerString: "9" },
  { id: 15, level: "Basic", question: "5 × 5 = ?", options: ["20","25","30","35"], answer: 1, answerString: "25" },
  { id: 16, level: "Basic", question: "6 + 7 = ?", options: ["12","13","14","15"], answer: 3, answerString: "13" },
  { id: 17, level: "Basic", question: "15 ÷ 3 = ?", options: ["4","5","6","7"], answer: 1, answerString: "5" },
  { id: 18, level: "Basic", question: "Sum of 8 + 9?", options: ["16","17","18","19"], answer: 1, answerString: "17" },
  { id: 19, level: "Basic", question: "10 × 4 = ?", options: ["30","40","50","60"], answer: 1, answerString: "40" },
  { id: 20, level: "Basic", question: "20 ÷ 4 = ?", options: ["4","5","6","7"], answer: 1, answerString: "5" },
  { id: 21, level: "Basic", question: "Square of 6?", options: ["30","36","42","48"], answer: 1, answerString: "36" },
  { id: 22, level: "Basic", question: "Square root of 64?", options: ["6","7","8","9"], answer: 2, answerString: "8" },
  { id: 23, level: "Basic", question: "7 × 3 = ?", options: ["18","19","20","21"], answer: 3, answerString: "21" },
  { id: 24, level: "Basic", question: "14 ÷ 2 = ?", options: ["6","7","8","9"], answer: 1, answerString: "7" },
  { id: 25, level: "Basic", question: "9 + 6 = ?", options: ["14","15","16","17"], answer: 1, answerString: "15" },
  { id: 26, level: "Basic", question: "12 - 5 = ?", options: ["6","7","8","9"], answer: 1, answerString: "7" },
  { id: 27, level: "Basic", question: "Multiplication of 8 × 5?", options: ["35","40","45","50"], answer: 1, answerString: "40" },
  { id: 28, level: "Basic", question: "Division 18 ÷ 3?", options: ["5","6","7","8"], answer: 1, answerString: "6" },
  { id: 29, level: "Basic", question: "Sum of 4 + 9?", options: ["12","13","14","15"], answer: 1, answerString: "13" },
  { id: 30, level: "Basic", question: "Square of 7?", options: ["47","48","49","50"], answer: 2, answerString: "49" },

  // Intermediate Level (31-60)
  { id: 31, level: "Intermediate", question: "Solve: 2x + 3 = 11", options: ["3","4","5","6"], answer: 2, answerString: "4" },
  { id: 32, level: "Intermediate", question: "Factorize: x² - 9", options: ["(x+3)(x-3)","(x+9)(x-1)","(x+1)(x-9)","(x+3)(x+3)"], answer: 0, answerString: "(x+3)(x-3)" },
  { id: 33, level: "Intermediate", question: "Value of π approx?", options: ["3.12","3.14","3.15","3.16"], answer: 1, answerString: "3.14" },
  { id: 34, level: "Intermediate", question: "Area of square side 5?", options: ["20","25","30","35"], answer: 1, answerString: "25" },
  { id: 35, level: "Intermediate", question: "Perimeter of rectangle 5×10?", options: ["25","30","35","30"], answer: 3, answerString: "30" },
  { id: 36, level: "Intermediate", question: "Solve: 5x = 25", options: ["4","5","6","7"], answer: 1, answerString: "5" },
  { id: 37, level: "Intermediate", question: "Simplify: 3(2 + x)", options: ["3x + 2","6 + 3x","2 + 3x","6x + 3"], answer: 1, answerString: "6 + 3x" },
  { id: 38, level: "Intermediate", question: "Cube of 3?", options: ["9","18","27","36"], answer: 2, answerString: "27" },
  { id: 39, level: "Intermediate", question: "HCF of 12 and 18?", options: ["3","6","12","18"], answer: 1, answerString: "6" },
  { id: 40, level: "Intermediate", question: "LCM of 4 and 6?", options: ["8","10","12","14"], answer: 2, answerString: "12" },
  { id: 41, level: "Intermediate", question: "Simplify: 5 + 2 × 3", options: ["11","21","16","13"], answer: 0, answerString: "11" },
  { id: 42, level: "Intermediate", question: "Square root of 144?", options: ["10","11","12","13"], answer: 2, answerString: "12" },
  { id: 43, level: "Intermediate", question: "Solve: x² = 16", options: ["2","4","8","16"], answer: 1, answerString: "4" },
  { id: 44, level: "Intermediate", question: "Angle sum of triangle?", options: ["90°","180°","270°","360°"], answer: 1, answerString: "180°" },
  { id: 45, level: "Intermediate", question: "Value of 2³ × 2²?", options: ["16","32","64","8"], answer: 1, answerString: "32" },
  { id: 46, level: "Intermediate", question: "Simplify: 15 ÷ (3×5)", options: ["1","2","3","4"], answer: 0, answerString: "1" },
  { id: 47, level: "Intermediate", question: "If x + 5 = 12, x = ?", options: ["5","6","7","8"], answer: 2, answerString: "7" },
  { id: 48, level: "Intermediate", question: "Area of circle radius 7?", options: ["154","145","150","160"], answer: 0, answerString: "154" },
  { id: 49, level: "Intermediate", question: "Perimeter of square side 8?", options: ["30","32","34","36"], answer: 1, answerString: "32" },
  { id: 50, level: "Intermediate", question: "Simplify: 10 - 2 × 3", options: ["4","6","8","12"], answer: 1, answerString: "4" },
  { id: 51, level: "Intermediate", question: "HCF of 15 and 25?", options: ["3","5","15","25"], answer: 2, answerString: "5" },
  { id: 52, level: "Intermediate", question: "LCM of 5 and 10?", options: ["10","15","20","25"], answer: 0, answerString: "10" },
  { id: 53, level: "Intermediate", question: "Simplify: 2² × 3²", options: ["12","16","36","9"], answer: 2, answerString: "36" },
  { id: 54, level: "Intermediate", question: "Solve: 3x + 7 = 16", options: ["2","3","4","5"], answer: 3, answerString: "3" },
  { id: 55, level: "Intermediate", question: "Square of 12?", options: ["144","121","132","124"], answer: 0, answerString: "144" },
  { id: 56, level: "Intermediate", question: "Cube root of 27?", options: ["2","3","9","6"], answer: 1, answerString: "3" },
  { id: 57, level: "Intermediate", question: "Angle of right triangle?", options: ["30°","45°","90°","60°"], answer: 2, answerString: "90°" },
  { id: 58, level: "Intermediate", question: "Simplify: 4² - 2²", options: ["8","12","16","14"], answer: 1, answerString: "12" },
  { id: 59, level: "Intermediate", question: "If 5x = 20, x = ?", options: ["2","3","4","5"], answer: 2, answerString: "4" },
  { id: 60, level: "Intermediate", question: "Perimeter of triangle sides 3,4,5?", options: ["10","12","14","15"], answer: 0, answerString: "12" },

  // Expert Level (61-90)
  { id: 61, level: "Expert", question: "Derivative of x²?", options: ["x","2x","x²","2"], answer: 1, answerString: "2x" },
  { id: 62, level: "Expert", question: "Integral of 2x dx?", options: ["x²","2x²","x","2x"], answer: 0, answerString: "x²" },
  { id: 63, level: "Expert", question: "Solve: 2x + 3 = 7", options: ["1","2","3","4"], answer: 1, answerString: "2" },
  { id: 64, level: "Expert", question: "Factorize: x² + 5x + 6", options: ["(x+2)(x+3)","(x+1)(x+6)","(x+2)(x+6)","(x+3)(x+5)"], answer: 0, answerString: "(x+2)(x+3)" },
  { id: 65, level: "Expert", question: "Limit of (x²-1)/(x-1) as x→1?", options: ["0","1","2","∞"], answer: 2, answerString: "2" },
  { id: 66, level: "Expert", question: "Derivative of sin(x)?", options: ["cos(x)","-cos(x)","sin(x)","-sin(x)"], answer: 0, answerString: "cos(x)" },
  { id: 67, level: "Expert", question: "Integral of cos(x) dx?", options: ["sin(x)","-sin(x)","cos(x)","-cos(x)"], answer: 0, answerString: "sin(x)" },
  { id: 68, level: "Expert", question: "Solve: x² - 4 = 0", options: ["1,2","-2,2","0,4","-4,4"], answer: 1, answerString: "-2,2" },
  { id: 69, level: "Expert", question: "Derivative of e^x?", options: ["x","e^x","e","1"], answer: 1, answerString: "e^x" },
  { id: 70, level: "Expert", question: "Integral of 1/x dx?", options: ["ln(x)","1/x²","x","e^x"], answer: 0, answerString: "ln(x)" },
  { id: 71, level: "Expert", question: "Solve: log₁₀100 = ?", options: ["1","2","10","100"], answer: 1, answerString: "2" },
  { id: 72, level: "Expert", question: "Simplify: (x²y³)(xy²)?", options: ["x³y⁵","x²y⁵","x³y⁶","x²y⁶"], answer: 0, answerString: "x³y⁵" },
  { id: 73, level: "Expert", question: "Derivative of ln(x)?", options: ["1/x","x","ln(x)","x²"], answer: 0, answerString: "1/x" },
  { id: 74, level: "Expert", question: "Solve: x³ = 27", options: ["2","3","4","5"], answer: 1, answerString: "3" },
  { id: 75, level: "Expert", question: "Limit of (sin x)/x as x→0?", options: ["0","1","∞","-1"], answer: 1, answerString: "1" },
  { id: 76, level: "Expert", question: "Derivative of cos(x)?", options: ["sin(x)","-sin(x)","cos(x)","-cos(x)"], answer: 1, answerString: "-sin(x)" },
  { id: 77, level: "Expert", question: "Integral of e^(2x) dx?", options: ["e^(2x)/2","2e^(2x)","e^(2x)","2e^(x)"], answer: 0, answerString: "e^(2x)/2" },
  { id: 78, level: "Expert", question: "Solve: 2x² - 8 = 0", options: ["x=1, -2","x=2,-2","x=2,-1","x=1,-1"], answer: 1, answerString: "x=2,-2" },
  { id: 79, level: "Expert", question: "Derivative of tan(x)?", options: ["sec²(x)","cosec²(x)","tan²(x)","1"], answer: 0, answerString: "sec²(x)" },
  { id: 80, level: "Expert", question: "Integral of 1/(1+x²)?", options: ["arctan(x)","arcsin(x)","arccos(x)","ln(x)"], answer: 0, answerString: "arctan(x)" },
  { id: 81, level: "Expert", question: "Simplify: (x³y²)/(xy)?", options: ["x²y","x²y²","x³y","x²y³"], answer: 0, answerString: "x²y" },
  { id: 82, level: "Expert", question: "Solve: 5x - 15 = 0", options: ["0","2","3","5"], answer: 2, answerString: "3" },
  { id: 83, level: "Expert", question: "Factorize: x² + 7x + 12", options: ["(x+3)(x+4)","(x+2)(x+5)","(x+1)(x+12)","(x+4)(x+5)"], answer: 0, answerString: "(x+3)(x+4)" },
  { id: 84, level: "Expert", question: "Derivative of x³?", options: ["x²","3x²","x³","3x³"], answer: 1, answerString: "3x²" },
  { id: 85, level: "Expert", question: "Integral of x dx?", options: ["x²/2","x²","2x","x/2"], answer: 0, answerString: "x²/2" },
  { id: 86, level: "Expert", question: "Solve: x² - 5x + 6 = 0", options: ["2,3","1,6","2,4","3,6"], answer: 0, answerString: "2,3" },
  { id: 87, level: "Expert", question: "Derivative of 5x?", options: ["5","5x","x","25"], answer: 0, answerString: "5" },
  { id: 88, level: "Expert", question: "Integral of 3x² dx?", options: ["x³","x³ + C","3x³","x² + C"], answer: 1, answerString: "x³ + C" },
  { id: 89, level: "Expert", question: "Simplify: (x²y³)²", options: ["x²y³","x⁴y⁶","x³y⁵","x⁴y⁵"], answer: 1, answerString: "x⁴y⁶" },
  { id: 90, level: "Expert", question: "Solve: 2x² + 3x - 2 = 0", options: ["1,-1","2,-2","1/2,-2","-1/2,1"], answer: 2, answerString: "1/2,-2" }
];
