const pakStudiesQuestions = [
  // Basic Level (1-30)
  { id: 1, level: "Basic", question: "Capital of Pakistan?", options: ["Lahore","Karachi","Islamabad","Peshawar"], answer: 2, answerString: "Islamabad" },
  { id: 2, level: "Basic", question: "National language of Pakistan?", options: ["English","Punjabi","Urdu","Sindhi"], answer: 2, answerString: "Urdu" },
  { id: 3, level: "Basic", question: "National flag color of Pakistan?", options: ["Green & White","Red & White","Blue & White","Yellow & Green"], answer: 0, answerString: "Green & White" },
  { id: 4, level: "Basic", question: "National animal of Pakistan?", options: ["Lion","Markhor","Tiger","Elephant"], answer: 1, answerString: "Markhor" },
  { id: 5, level: "Basic", question: "National flower of Pakistan?", options: ["Rose","Jasmine","Tulip","Sunflower"], answer: 1, answerString: "Jasmine" },
  { id: 6, level: "Basic", question: "Independence day of Pakistan?", options: ["14 August","23 March","1 January","25 December"], answer: 0, answerString: "14 August" },
  { id: 7, level: "Basic", question: "Father of Nation?", options: ["Allama Iqbal","Quaid-e-Azam","Liaquat Ali Khan","Ayub Khan"], answer: 1, answerString: "Quaid-e-Azam" },
  { id: 8, level: "Basic", question: "National fruit of Pakistan?", options: ["Mango","Apple","Banana","Orange"], answer: 0, answerString: "Mango" },
  { id: 9, level: "Basic", question: "Currency of Pakistan?", options: ["Rupee","Dollar","Pound","Euro"], answer: 0, answerString: "Rupee" },
  { id: 10, level: "Basic", question: "Which ocean is near Pakistan?", options: ["Atlantic","Pacific","Indian","Arctic"], answer: 2, answerString: "Indian" },
  { id: 11, level: "Basic", question: "Largest city of Pakistan?", options: ["Karachi","Lahore","Islamabad","Quetta"], answer: 0, answerString: "Karachi" },
  { id: 12, level: "Basic", question: "Second largest city of Pakistan?", options: ["Lahore","Karachi","Islamabad","Peshawar"], answer: 0, answerString: "Lahore" },
  { id: 13, level: "Basic", question: "National bird of Pakistan?", options: ["Parrot","Chukar","Eagle","Peacock"], answer: 1, answerString: "Chukar" },
  { id: 14, level: "Basic", question: "National sport of Pakistan?", options: ["Cricket","Hockey","Football","Squash"], answer: 1, answerString: "Hockey" },
  { id: 15, level: "Basic", question: "National language script?", options: ["Arabic","Urdu","Persian","English"], answer: 1, answerString: "Urdu" },
  { id: 16, level: "Basic", question: "Quaid-e-Azam was born in?", options: ["Karachi","Lahore","Nawabshah","Quetta"], answer: 0, answerString: "Karachi" },
  { id: 17, level: "Basic", question: "Pakistan Day is?", options: ["23 March","14 August","6 September","25 December"], answer: 0, answerString: "23 March" },
  { id: 18, level: "Basic", question: "National anthem composer?", options: ["Ahmed Ghulamali Chagla","Allama Iqbal","Nusrat Fateh Ali Khan","Liaquat Ali Khan"], answer: 0, answerString: "Ahmed Ghulamali Chagla" },
  { id: 19, level: "Basic", question: "Founder of Pakistan movement?", options: ["Allama Iqbal","Quaid-e-Azam","Liaquat Ali Khan","Sir Syed Ahmed Khan"], answer: 0, answerString: "Allama Iqbal" },
  { id: 20, level: "Basic", question: "State religion of Pakistan?", options: ["Islam","Christianity","Hinduism","Buddhism"], answer: 0, answerString: "Islam" },
  { id: 21, level: "Basic", question: "National motto of Pakistan?", options: ["Unity, Faith, Discipline","Peace & Love","Freedom & Justice","Work & Progress"], answer: 0, answerString: "Unity, Faith, Discipline" },
  { id: 22, level: "Basic", question: "Pakistan shares border with?", options: ["India","Afghanistan","Iran","All"], answer: 3, answerString: "All" },
  { id: 23, level: "Basic", question: "Which river flows in Pakistan?", options: ["Ganga","Indus","Yamuna","Brahmaputra"], answer: 1, answerString: "Indus" },
  { id: 24, level: "Basic", question: "Islamic calendar starts with?", options: ["Hijri","Gregorian","Solar","Lunar"], answer: 0, answerString: "Hijri" },
  { id: 25, level: "Basic", question: "First capital of Pakistan?", options: ["Karachi","Islamabad","Lahore","Quetta"], answer: 0, answerString: "Karachi" },
  { id: 26, level: "Basic", question: "Current capital of Pakistan?", options: ["Karachi","Islamabad","Lahore","Quetta"], answer: 1, answerString: "Islamabad" },
  { id: 27, level: "Basic", question: "Pakistan national airline?", options: ["PIA","Emirates","Qatar Airways","Air India"], answer: 0, answerString: "PIA" },
  { id: 28, level: "Basic", question: "Pakistan Independence from?", options: ["Britain","France","Portugal","Netherlands"], answer: 0, answerString: "Britain" },
  { id: 29, level: "Basic", question: "Pakistan’s largest province?", options: ["Punjab","Sindh","Balochistan","KPK"], answer: 0, answerString: "Punjab" },
  { id: 30, level: "Basic", question: "Pakistan’s smallest province?", options: ["Sindh","Punjab","Balochistan","KPK"], answer: 3, answerString: "KPK" },

  // Intermediate Level (31-60)
  { id: 31, level: "Intermediate", question: "First Governor General of Pakistan?", options: ["Jinnah","Liaquat Ali Khan","Iskander Mirza","Ayub Khan"], answer: 0, answerString: "Jinnah" },
  { id: 32, level: "Intermediate", question: "First Prime Minister of Pakistan?", options: ["Jinnah","Liaquat Ali Khan","Iskander Mirza","Bhutto"], answer: 1, answerString: "Liaquat Ali Khan" },
  { id: 33, level: "Intermediate", question: "Who introduced Pakistan Resolution?", options: ["Allama Iqbal","Jinnah","Liaquat Ali Khan","Ishaq Khan"], answer: 0, answerString: "Allama Iqbal" },
  { id: 34, level: "Intermediate", question: "Pakistan Resolution passed in?", options: ["1940","1947","1939","1956"], answer: 0, answerString: "1940" },
  { id: 35, level: "Intermediate", question: "Where was Pakistan Resolution passed?", options: ["Karachi","Lahore","Islamabad","Quetta"], answer: 1, answerString: "Lahore" },
  { id: 36, level: "Intermediate", question: "First Constitution of Pakistan?", options: ["1956","1973","1962","1947"], answer: 0, answerString: "1956" },
  { id: 37, level: "Intermediate", question: "Current Constitution of Pakistan?", options: ["1956","1973","1962","1947"], answer: 1, answerString: "1973" },
  { id: 38, level: "Intermediate", question: "Pakistan became Republic in?", options: ["1947","1956","1962","1973"], answer: 1, answerString: "1956" },
  { id: 39, level: "Intermediate", question: "First martial law imposed by?", options: ["Ayub Khan","Iskander Mirza","Zia-ul-Haq","Bhutto"], answer: 1, answerString: "Iskander Mirza" },
  { id: 40, level: "Intermediate", question: "Longest-serving president of Pakistan?", options: ["Ayub Khan","Zia-ul-Haq","Pervez Musharraf","Iskander Mirza"], answer: 0, answerString: "Ayub Khan" },
  { id: 41, level: "Intermediate", question: "First female Prime Minister of Pakistan?", options: ["Benazir Bhutto","Fatima Jinnah","Maryam Nawaz","Hina Rabbani"], answer: 0, answerString: "Benazir Bhutto" },
  { id: 42, level: "Intermediate", question: "Pakistan shares border with India in?", options: ["East","West","North","South"], answer: 0, answerString: "East" },
  { id: 43, level: "Intermediate", question: "Pakistan shares border with Afghanistan in?", options: ["East","West","North","South"], answer: 1, answerString: "West" },
  { id: 44, level: "Intermediate", question: "Largest dam in Pakistan?", options: ["Tarbela","Mangla","Warsak","Hub"], answer: 0, answerString: "Tarbela" },
  { id: 45, level: "Intermediate", question: "National poet of Pakistan?", options: ["Allama Iqbal","Faiz Ahmed Faiz","Ghalib","Iqbal"], answer: 0, answerString: "Allama Iqbal" },
  { id: 46, level: "Intermediate", question: "National language first script?", options: ["Arabic","Persian","Urdu","Latin"], answer: 1, answerString: "Persian" },
  { id: 47, level: "Intermediate", question: "Pakistan’s largest province by area?", options: ["Punjab","Sindh","Balochistan","KPK"], answer: 2, answerString: "Balochistan" },
  { id: 48, level: "Intermediate", question: "Pakistan joined UN in?", options: ["1945","1947","1948","1950"], answer: 2, answerString: "1947" },
  { id: 49, level: "Intermediate", question: "Pakistan’s first atomic test?", options: ["Chagai-I","Chagai-II","Ravi-I","Ravi-II"], answer: 0, answerString: "Chagai-I" },
  { id: 50, level: "Intermediate", question: "Pakistan national assembly consists of?", options: ["100","200","342","450"], answer: 2, answerString: "342" },
  { id: 51, level: "Intermediate", question: "Governor of a province is?", options: ["Elected","Appointed","Hereditary","Random"], answer: 1, answerString: "Appointed" },
  { id: 52, level: "Intermediate", question: "Pakistan’s Independence struggle leader?", options: ["Quaid-e-Azam","Allama Iqbal","Liaquat Ali Khan","Jinnah"], answer: 3, answerString: "Jinnah" },
  { id: 53, level: "Intermediate", question: "Pakistan gained independence in?", options: ["1940","1945","1947","1956"], answer: 2, answerString: "1947" },
  { id: 54, level: "Intermediate", question: "Constitution of 1973 enforced by?", options: ["Zulfikar Ali Bhutto","Zia-ul-Haq","Ayub Khan","Liaquat Ali Khan"], answer: 0, answerString: "Zulfikar Ali Bhutto" },
  { id: 55, level: "Intermediate", question: "Allama Iqbal birthplace?", options: ["Sialkot","Lahore","Karachi","Quetta"], answer: 0, answerString: "Sialkot" },
  { id: 56, level: "Intermediate", question: "Lahore Resolution also known as?", options: ["Pakistan Resolution","Independence Resolution","Freedom Resolution","All"], answer: 0, answerString: "Pakistan Resolution" },
  { id: 57, level: "Intermediate", question: "First Muslim league president?", options: ["Jinnah","Liaquat Ali Khan","Allama Iqbal","Bhutto"], answer: 0, answerString: "Jinnah" },
  { id: 58, level: "Intermediate", question: "Pakistan’s largest port?", options: ["Karachi","Gwadar","Qasim","Port Qasim"], answer: 0, answerString: "Karachi" },
  { id: 59, level: "Intermediate", question: "Pakistan joined OIC in?", options: ["1969","1971","1973","1975"], answer: 0, answerString: "1969" },
  { id: 60, level: "Intermediate", question: "National monument of Pakistan?", options: ["Mazar-e-Quaid","Minar-e-Pakistan","Faisal Mosque","Tomb of Allama Iqbal"], answer: 1, answerString: "Minar-e-Pakistan" },

  // Expert Level (61-90)
  { id: 61, level: "Expert", question: "First martial law administrator of Pakistan?", options: ["Ayub Khan","Iskander Mirza","Zia-ul-Haq","Pervez Musharraf"], answer: 1, answerString: "Iskander Mirza" },
  { id: 62, level: "Expert", question: "Second martial law in Pakistan?", options: ["Ayub Khan","Zia-ul-Haq","Pervez Musharraf","Iskander Mirza"], answer: 0, answerString: "Ayub Khan" },
  { id: 63, level: "Expert", question: "Third martial law in Pakistan?", options: ["Zia-ul-Haq","Musharraf","Ayub Khan","Iskander Mirza"], answer: 0, answerString: "Zia-ul-Haq" },
  { id: 64, level: "Expert", question: "Fourth martial law in Pakistan?", options: ["Musharraf","Zia-ul-Haq","Ayub Khan","Iskander Mirza"], answer: 0, answerString: "Musharraf" },
  { id: 65, level: "Expert", question: "First constitution of Pakistan was abrogated by?", options: ["Ayub Khan","Iskander Mirza","Zia-ul-Haq","Liaquat Ali Khan"], answer: 1, answerString: "Iskander Mirza" },
  { id: 66, level: "Expert", question: "Second constitution of Pakistan replaced in?", options: ["1962","1973","1956","1947"], answer: 0, answerString: "1962" },
  { id: 67, level: "Expert", question: "Pakistan adopted Islamic provisions in Constitution?", options: ["1962","1973","1956","1985"], answer: 1, answerString: "1973" },
  { id: 68, level: "Expert", question: "First martial law declared year?", options: ["1958","1969","1977","1999"], answer: 0, answerString: "1958" },
  { id: 69, level: "Expert", question: "Second martial law declared year?", options: ["1969","1977","1999","1958"], answer: 0, answerString: "1969" },
  { id: 70, level: "Expert", question: "Third martial law declared year?", options: ["1977","1999","1958","1969"], answer: 0, answerString: "1977" },
  { id: 71, level: "Expert", question: "Fourth martial law declared year?", options: ["1999","1977","1969","1958"], answer: 0, answerString: "1999" },
  { id: 72, level: "Expert", question: "Islamabad declared capital in?", options: ["1960","1959","1965","1970"], answer: 1, answerString: "1959" },
  { id: 73, level: "Expert", question: "Constitution of Pakistan passed in?", options: ["1956","1962","1973","1985"], answer: 2, answerString: "1973" },
  { id: 74, level: "Expert", question: "First speaker of National Assembly?", options: ["Qasim","Liaquat Ali Khan","Jinnah","Ayub Khan"], answer: 0, answerString: "Qasim" },
  { id: 75, level: "Expert", question: "Pakistan joined Commonwealth in?", options: ["1947","1956","1962","1973"], answer: 0, answerString: "1947" },
  { id: 76, level: "Expert", question: "Pakistan joined SAARC in?", options: ["1985","1986","1987","1988"], answer: 2, answerString: "1987" },
  { id: 77, level: "Expert", question: "Pakistan became nuclear power in?", options: ["1974","1998","1983","2000"], answer: 1, answerString: "1998" },
  { id: 78, level: "Expert", question: "Pakistani Prime Minister executed in 1979?", options: ["Zulfikar Ali Bhutto","Benazir Bhutto","Liaquat Ali Khan","Muhammad Khan Junejo"], answer: 0, answerString: "Zulfikar Ali Bhutto" },
  { id: 79, level: "Expert", question: "Pakistan’s first female foreign minister?", options: ["Hina Rabbani Khar","Benazir Bhutto","Fatima Jinnah","Tehmina Durrani"], answer: 0, answerString: "Hina Rabbani Khar" },
  { id: 80, level: "Expert", question: "Pakistan became member of IMF in?", options: ["1947","1955","1960","1971"], answer: 1, answerString: "1955" },
  { id: 81, level: "Expert", question: "Pakistan’s first military ruler?", options: ["Ayub Khan","Iskander Mirza","Zia-ul-Haq","Musharraf"], answer: 1, answerString: "Iskander Mirza" },
  { id: 82, level: "Expert", question: "East Pakistan became Bangladesh in?", options: ["1971","1965","1973","1958"], answer: 0, answerString: "1971" },
  { id: 83, level: "Expert", question: "Who wrote Pakistan national anthem?", options: ["Hafeez Jalandhari","Allama Iqbal","Faiz Ahmed Faiz","Ahmed Chagla"], answer: 0, answerString: "Hafeez Jalandhari" },
  { id: 84, level: "Expert", question: "Pakistan’s first Chief Justice?", options: ["Mohammad Munir","Anwarul Haq","Iftikhar Chaudhry","Saad Saud"], answer: 0, answerString: "Mohammad Munir" },
  { id: 85, level: "Expert", question: "Pakistan’s first Governor General?", options: ["Jinnah","Iskander Mirza","Liaquat Ali Khan","Ayub Khan"], answer: 0, answerString: "Jinnah" },
  { id: 86, level: "Expert", question: "Pakistan joined OIC first summit in?", options: ["1969","1970","1971","1972"], answer: 0, answerString: "1969" },
  { id: 87, level: "Expert", question: "First constitution of Pakistan abrogated year?", options: ["1956","1958","1962","1973"], answer: 1, answerString: "1958" },
  { id: 88, level: "Expert", question: "Second constitution of Pakistan replaced year?", options: ["1962","1973","1956","1985"], answer: 0, answerString: "1962" },
  { id: 89, level: "Expert", question: "Pakistan’s first foreign minister?", options: ["Zulfiqar Ali Bhutto","Liaquat Ali Khan","Chaudhry Zafrullah Khan","Allama Iqbal"], answer: 2, answerString: "Chaudhry Zafrullah Khan" },
  { id: 90, level: "Expert", question: "Pakistan’s first nuclear scientist?", options: ["Dr. Abdul Qadeer Khan","Dr. Ishrat Hussain","Dr. Samar Mubarakmand","Dr. Atta-ur-Rahman"], answer: 0, answerString: "Dr. Abdul Qadeer Khan" }
];
